# -*- coding: utf-8 -*-
"""First_Program_Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q9yNrCC8E--pA0zIGTQBhQAI7oUl8PCf
"""

first_Number = int(input("Enter_First_number"))
print(first_Number)

Second_Number=int(input("Enter_Second_Number"))

print(Second_Number)

ope= input('Any_Operation')



if (ope=='+'):

  print(first_Number+Second_Number)

elif (ope=='-'):

     print(first_Number-Second_Number)

else:

  print("Operation_Not_Found")